# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

name: line-rating
channels:
  - conda-forge
  - bioconda
  - http://conda.anaconda.org/gurobi
dependencies:
  - python>=3.8
  - pip
  - mamba # esp for windows build

  - pypsa>=0.18

  # Dependencies of the workflow itself
  - xlrd
  - openpyxl
  - pycountry
  - seaborn
  - snakemake-minimal
  - memory_profiler
  - yaml
  - pytables
  - lxml
  - powerplantmatching>=0.4.8
  - numpy
  - pandas
  - geopandas
  - xarray
  - netcdf4
  - networkx
  - scipy
  - shapely
  - progressbar2
  - pyomo
  - matplotlib
  - proj
  - dask

  # Keep in conda environment when calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - descartes
  - rasterio

  # PyPSA-Eur-Sec Dependencies
  - geopy
  - tqdm
  - pytz
  - country_converter
  - tabula-py

# Develop
  - pre-commit

  - pip:
    - gurobipy
    - vresutils==0.3.1
    - tsam>=1.1.0
    - git+https://github.com/PyPSA/atlite.git
    - git+https://github.com/PyPSA/pypsa.git
