# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

scenario_2020:
  rating: ["", 1.3, 1.5, 1.8, 2.0]
  angle: ""
  clusters: "all"
  opts: "Co2L-BL-Ep"
  year: 2020
  figure:
    [
      "operation_map",
      "capacity_map",
      "congestion_map",
      "curtailment_bar",
      "capacity_bar",
      "cost_bar",
      "relative_curtailment_bar",
      "historical_curtailment_bar",
      "congestion_correlation",
      "potential_correlation",
      "congestion_duration_curve",
    ]
  sensitivity:
    [
    "cost",
    "curtailment",
    "capacity"
    ]

scenario_2030:
  rating: ["", 1.3, 1.5, 1.8, 2.0]
  angle: ""
  clusters: "all"
  opts: "Co2L-RE0.8-Ep"
  year: 2030
  figure:
    [
      "operation_map",
      "capacity_map",
      "congestion_map",
      "curtailment_bar",
      "capacity_bar",
      "cost_bar",
      "relative_curtailment_bar",
      "historical_curtailment_bar",
      "potential_correlation",
      "congestion_correlation",
      "potential_correlation",
      "congestion_duration_curve",
    ]
  sensitivity:
    [
    "cost",
    "curtailment",
    "capacity"
    ]

scenario_2030_unbound:
  rating: ""
  angle: ""
  clusters: "all"
  opts: "Co2L-RE0.8-Ep"
  year: 2030
  figure:
    [
      "operation_map",
      "capacity_map",
      "congestion_map",
      "curtailment_bar",
      "capacity_bar",
      "cost_bar",
      "relative_curtailment_bar",
      "historical_curtailment_bar",
      "potential_correlation",
      "congestion_correlation",
      "potential_correlation",
      "congestion_duration_curve",
    ]
  sensitivity:
    [
    "cost",
    "curtailment",
    "capacity"
    ]

test:
  rating: ["", 1.3]
  angle: [30, 45]
  clusters: [5]
  opts: ["Co2L-24H-BL", "Co2L-24H-RE0.8"]
  year: [2020, 2030]
  figure:
    [
      "operation_map",
      "capacity_map",
      "curtailment_bar",
      "capacity_bar",
      "relative_curtailment_bar",
      "historical_curtailment_bar",
      "potential_correlation",
      "sensitivity_cost"
    ]

solving:
  options:
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: true
    min_iterations: 1
    max_iterations: 1
    clip_p_max_pu: 0.01
    skip_iterations: true
    track_iterations: false
  solver:
    name: gurobi
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-5
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200

electricity:
  # parameters used for the min renewable constraint
  renewable_aim: # installed capacity aim 2030 of BMWi for Germany https://www.bmwi.de/Redaktion/DE/Downloads/Energie/220111_eroeffnungsbilanz_klimaschutz.pdf?__blob=publicationFile&v=22
    onwind: 100 #GW
    offwind: 30 #GW
    solar: 200 #GW
    biomass: 0 #if not given set to 0
  # parameters used for the base load constraint
  base_load:
    lignite: 0.2 #min_p_pu value for lignite
    nuclear: 0.354

plotting:
  map:
    figsize: [8, 4]
    boundaries: [5.5, 15.5, 47, 55]
    #If None or commented out the plot_main.py automatically calculates the bus and line factor. If factor is given, then the factor is taken.
    capacity:
      bus_size_factor: 1.2e-5
      line_width_factor: 3.e-4
      refsize: 5000 # at what capacity should circle be drawn
    operation:
      bus_size_factor: 5.e-5
      line_width_factor: 7.e-3
      refsize: 1000 # at what capacity should circle be drawn
    curtailment:
      bus_size_factor: 8.e-10
      line_width_factor: 1.e-3
      refsize: 1.e+6 # at what capacity should circle be drawn
    utilization:
      refsize: 1000 # at what capacity should circle be drawn
    congestion:
      refsize: 1.e+6 # at what capacity should circle be drawn
      line_width_factor: 1
  bar:
    operation:
      figsize: [5, 5]
    cost:
      figsize: [5, 5]
    capacity:
      figsize: [5, 8]
    relative_curtailment:
      figsize: [6, 4]
    curtailment:
      figsize: [6,4]
