# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

scenario:
  rating: ['dlr', 'slr']
  clusters: ["all"]
  opts: ["CO2L"]
  year: [2020, 2030]

solving:
  options:
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: true
    min_iterations: 1
    max_iterations: 1
    clip_p_max_pu: 0.01
    skip_iterations: true
    track_iterations: false
  solver:
    name: gurobi
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-6
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
